blog/urls.py
from django.urls import path
from django.views.generic.dates import ArchiveIndexView, YearArchiveView

from . import views
from .models import Blog


urlpatterns = [
    # Index (home page)
    path('', views.Index.as_view(), name='index'),
    # Archive
    path('archive/', views.BlogArchiveView.as_view(), name='archive'),
    # Archive by tag
    path('category/<str:tag>/', views.TagArchiveView.as_view(), name='blog-tag-archive'),
    # Archive by year
    path('<int:year>/', YearArchiveView.as_view(model=Blog, date_field="post_date", make_object_list=True),
         name="blog-year-archive"),
    # Blog detail specified by date and slug
    path('<int:year>/<int:month>/<int:day>/<slug:slug>/', views.BlogDetailView.as_view(), name='blog-detail'),
    # Deprecated
    path('blog-author/<int:pk>', views.BlogAuthorDetailView.as_view(), name='blog-author-detail'),
    # Page introducing this blog website
    path('about-this-blog', views.AboutThisBlogView.as_view(), name='about-this-blog'),
    # Page introducing myself
    path('about-me', views.AboutMeView.as_view(), name='about-me'),
]

urlpatterns += [
    path('add/', views.BlogCreate.as_view(), name='blog-add'), 
    path('<int:year>/<int:month>/<int:day>/<slug:slug>/update/', views.BlogUpdate.as_view(), name='blog-update'),
    path('<int:year>/<int:month>/<int:day>/<slug:slug>/delete/', views.BlogDelete.as_view(), name='blog-delete'),
    path('<int:year>/<int:month>/<int:day>/<slug:slug>/<seqnum>/update/', views.BlogSectionUpdate.as_view(),
         name='blog-section-update'),
    path('preview-markdown', views.PreviewMarkdownView.as_view(), name='preview-markdown'),
]

pensieve/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.views.generic import RedirectView


urlpatterns = [
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls')),
    path('martor/', include('martor.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += [
    path('', RedirectView.as_view(url='/blog/')),
]

blog/models.py
from datetime import date

from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse


class Tag(models.Model):
    """
    Model representing a tag.

    One blog can have multi tags, one tag can be used for multi blogs.
    """
    tag = models.CharField(max_length=20, help_text="Define a tag.")

    def __str__(self):
        """
        String represent the model object.
        """
        return self.tag


class BlogAuthor(models.Model):
    """
    Model representing a blog author.
    """
    name = models.ForeignKey(User,on_delete=models.PROTECT)
    biography = models.TextField()

    def __str__(self):
        """
        String representing the Model object.
        """
        return self.name.username

    def get_absolute_url(self):
        """
        Return the url to access a particular blog-author instance.
        """
        return reverse('blog-author-detail', args=[str(self.id)]) 


class Blog(models.Model):
    """
    Model representing a blog.
    """
    blog_author = models.ForeignKey(BlogAuthor, on_delete=models.PROTECT, default=1)
    post_date = models.DateField(default=date.today)
    tags = models.ManyToManyField(Tag)
    title = models.CharField(max_length=50)
    slug = models.CharField(max_length=50, unique_for_date="post_date")
    content = models.TextField(blank=True)
    content_xml = models.TextField(blank=True)

    class Meta:
        ordering = ['-post_date']

    def __str__(self):
        """
        String representing the blog instance.
        """
        return self.title

    def get_absolute_url(self):
        """
        Return the url to access a particular blog instance.
        """
        return reverse(
            'blog-detail', 
            kwargs={
                'year': self.post_date.year,
                'month': self.post_date.month,
                'day': self.post_date.day,
                'slug': self.slug
            }
        )


class BlogComment(models.Model):
    """
    Model representing a comment against a blog post.
    """
    comment_author = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    post_date = models.DateTimeField(auto_now_add=True)
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE)
    content = models.TextField(max_length=500)

    def __str__(self):
        """
        String representing the Model object.
        """
        title_len = 75
        if len(self.content) > title_len:
            title_string = self.content[:title_len] + "..."
        else:
            title_string = self.content
        return title_string

blog/forms.py
from django import forms

from .models import Blog


class BlogModelForm(forms.ModelForm):
    class Meta:
        model = Blog
        fields = ['title', 'slug', 'content', 'blog_author', 'post_date', 'tags']

        #widgets = {
        #    'content': forms.Textarea(attrs={'cols': '120', 'rows': '40'}),
        #}

blog/views.py
import collections
import logging
import xml.etree.ElementTree as ET
from datetime import date

from django.contrib.auth.mixins import PermissionRequiredMixin
from django.http import JsonResponse
from django.shortcuts import render, get_object_or_404
from django.urls import reverse_lazy
from django.views import generic, View
from django.views.generic.base import TemplateView
from django.views.generic.dates import ArchiveIndexView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
import markdown

from .markdown_processor import MarkdownProcessor
from .models import Blog, BlogAuthor, BlogComment, Tag

logging.basicConfig(format='%(asctime)s %(levelname)s %(message)s', level=logging.INFO)
logger = logging.getLogger('django')


class Index(ArchiveIndexView):
    """
    Class-based view for home.

    Get all blogs ordered by date in descending order.
    In the template, comments detail won't be displayed.
    """
    allow_empty = True
    date_field = "post_date"
    model = Blog
    template_name = 'index.html'


class BlogArchiveView(ArchiveIndexView):
    """
    Archive blogs by dates and tag.
    """
    allow_empty = True
    date_field = "post_date"
    model = Blog

    def get_context_data(self, **kwargs):
        """
        Extends context by adding data grouped by date and tag to context.
        """
        context = super().get_context_data(**kwargs)
        object_dict_sorted_by_year = {}
        for date in context['date_list']:
            year = date.year
            object_dict_sorted_by_year[year] = Blog.objects.filter(post_date__year=year)
        ordered_object_dict_sorted_by_year = collections.OrderedDict(sorted(object_dict_sorted_by_year.items(), reverse=True))
        context['object_dict_sorted_by_year'] = ordered_object_dict_sorted_by_year
        
        object_dict_sorted_by_tag = {}
        for tag in Tag.objects.all():
            related_objects = tag.blog_set.all()
            if related_objects:
                object_dict_sorted_by_tag[tag.tag] = related_objects
        ordered_object_dict_sorted_by_tag = collections.OrderedDict(sorted(object_dict_sorted_by_tag.items()))
        context['object_dict_sorted_by_tag'] = ordered_object_dict_sorted_by_tag

        return context


class TagArchiveView(generic.ListView):
    """
    Archive by tag.

    The URL should be 'category/<str:tag>/'.
    """
    model = Blog
    template_name = "blog/blog_archive_tag.html"

    def get_queryset(self):
        tag = get_object_or_404(Tag, tag=self.kwargs['tag'])
        blog_with_tag = Blog.objects.filter(tags=tag)
        return blog_with_tag

    def get_context_data(self, **kwargs):
        """
        Add the tag name to context.
        """
        context = super().get_context_data(**kwargs)
        context['tag'] = self.kwargs['tag']
        return context


class BlogDetailView(generic.DetailView):
    """
    Class-based view for one particular blog.
    """
    context_object_name = "blog"

    def get_queryset(self):
        post_date = date(self.kwargs['year'], self.kwargs['month'], self.kwargs['day'])
        return Blog.objects.filter(post_date=post_date, slug=self.kwargs['slug'])

    def get_context_data(self, **kwargs):
        """
        Add extra data ('comment number') to context.

        BETTER WAY:
            In template, use 'blog.blogcomment_set.all.count' to get the count.
        """
        context = super().get_context_data(**kwargs)
        post_date = date(self.kwargs['year'], self.kwargs['month'], self.kwargs['day'])
        blog = get_object_or_404(Blog, post_date=post_date, slug=self.kwargs['slug'])
        comment_number = BlogComment.objects.filter(blog=blog).count()
        context['comment_number'] = comment_number
        return context


class BlogCreate(PermissionRequiredMixin, CreateView):
    """
    Generic class-based view for adding a new blog.
    """
    model = Blog
    fields = ['title', 'slug', 'content', 'blog_author', 'post_date', 'tags']
    permission_required = 'blog.add_blog'

    def form_valid(self, form):
        md = MarkdownProcessor(form.instance.content)
        md.to_xml()
        form.instance.content_xml = ET.tostring(md.root, encoding='unicode')
        return super().form_valid(form)


class BlogUpdate(PermissionRequiredMixin, UpdateView):
    """
    Generic class-based view for updating a particular blog.
    """
    model = Blog
    fields = ['content']
    permission_required = 'blog.change_blog'

    def form_valid(self, form):
        md = MarkdownProcessor(form.instance.content)
        md.to_xml()
        form.instance.content_xml = ET.tostring(md.root, encoding='unicode')
        return super().form_valid(form)


class PreviewMarkdownView(View):
    """
    Converts markdown to HTML.
    """
    def post(self, request, *args, **kwargs):
        # Return HTML string transformed from markdown.
        return JsonResponse(
            {
                'html': markdown.markdown(request.POST["origin-markdown"])
            },
            json_dumps_params={'ensure_ascii': False}
        )


class BlogSectionUpdate(PermissionRequiredMixin, View):
    """
    Class-based view for updating only sections.
    """
    permission_required = 'blog.change_blog'

    def get(self, request, *args, **kwargs):
        blog = self.get_blog(**kwargs)
        seqnum = kwargs["seqnum"]
        logger.debug("seqnum: {}".format(seqnum))
        root, section = self.parse_xml(blog, seqnum)

        return JsonResponse(
            {
                'section_text': self.extract_and_join_element_text(section, "\n")
            },
            json_dumps_params={'ensure_ascii': False}
        )

    def post(self, request, *args, **kwargs):
        blog = self.get_blog(**kwargs)
        seqnum = kwargs["seqnum"]
        logger.debug("seqnum: {}".format(seqnum))
        root, old_section = self.parse_xml(blog, seqnum)

        # Convert plain text to XML tree.
        md = MarkdownProcessor(request.POST["section-text"])
        last_id_list = list(map(int, seqnum.split(".")))
        last_id_list[-1] = last_id_list[-1] - 1 if last_id_list[-1] > 0 else last_id_list[-1]
        md.id_list = last_id_list
        md.to_xml()

        # Update section element within XML tree via replacing old section element.
        new_section = md.root.find("h")
        logger.debug("Update element '{}' to '{}'".format(
            ET.tostring(old_section, encoding='unicode'),
            ET.tostring(new_section, encoding='unicode'))
        )
        parent_map = dict((c, p) for p in root.iter() for c in p)
        parent = parent_map[old_section]
        logger.debug("Parent element before replacing child: {}".format(ET.tostring(parent, encoding='unicode')))
        self.replace_child(parent, new_section, old_section)
        logger.debug("XML root after replacing child: {}".format(ET.tostring(md.root, encoding='unicode')))

        # Concatenate inner text of XML elements and update blog's fields 'content' and 'content_xml'.
        blog.content = self.extract_and_join_element_text(root, "\n")
        logger.debug("Update blog's content field to: {}".format(blog.content))
        blog.content_xml = ET.tostring(root, encoding='unicode')
        logger.debug("Update blog's content_xml field to: {}".format(blog.content_xml))
        blog.save()

        # Return HTML string transformed by markdown.
        return JsonResponse(
            {
                'section_html': markdown.markdown(request.POST["section-text"])
            },
            json_dumps_params={'ensure_ascii': False}
        )

    @staticmethod
    def replace_child(parent, new, old):
        """
        Replaces a sub-element.

        :param parent: Parent element whose child would be replaced
        :param new: New XML element
        :param old: Old XML element to be replaced
        :return: None
        """
        parent.insert(list(parent).index(old), new)
        parent.remove(old)

    @staticmethod
    def get_blog(**kwargs):
        """
        Returns blog object identified by post date and slug.

        :param kwargs:
        :return: instance of Blog model
        """
        post_date = "-".join(map(str, [kwargs['year'], kwargs['month'], kwargs['day']]))

        # Find blog by post date and slug.
        blog = Blog.objects.get(post_date=post_date, slug=kwargs['slug'])
        logger.debug("blog title: {}".format(blog.title))

        return blog

    @staticmethod
    def parse_xml(blog, seqnum):
        """
        Parses from blog's field content_xml.

        :param blog: An instance of Blog model
        :param seqnum: specific sequence number
        :return: a tuple of root element and specific section
        """
        # Parses an XML section from string.
        root = ET.fromstring(blog.content_xml)
        logger.debug("root: {}".format(ET.tostring(root, encoding='unicode')))
        section = root.find(".//*[@id='{}']".format(seqnum))
        logger.debug("section: {}".format(ET.tostring(section, encoding='unicode')))

        return root, section

    def extract_and_join_element_text(self, element, sep):
        """
        Join inner text of given element and all of its children.

        :param element: An instance of xml Element.
        :param sep: String as separator.
        :return: The concatenated string.
        """
        logger.debug(sep.join(list(self.itertext(element))))
        return sep.join(list(self.itertext(element)))

    def itertext(self, element):
        """Create text iterator.

        The iterator loops over the element and all subelements in document
        order, returning all inner text.
        """
        tag = element.tag
        if not isinstance(tag, str) and tag is not None:
            return
        t = element.text
        if t:
            yield t
        else:
            yield ""
        for sub_element in element:
            yield from self.itertext(sub_element)

blog/templates/about_me.html
{% extends "base_generic.html" %}

{% block content %}
<p>Seems would not come soon...</p>
{% endblock %}

blog/templates/about_this_blog.html
{% extends "base_generic.html" %}

{% block content %}
<p>Coming soon...</p>
{% endblock %}

blog/templates/base_generic.html
<!DOCTYPE html>
<html lang="en">
  
  <head>
    {% block title %}<title>pensieve</title>{% endblock %}
    <meta charset='utf-8'>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% load static %}
    <link rel="stylesheet" href="{% static 'blog/css/styles.css' %}">
    <script src="{% static 'blog/javascript/nav.js' %}"></script>
  </head>
  
  <body>
    <header class="theme-background">
      <p id="site-name"><a class="theme-text-color header" href="{% url 'index' %}">Pensieve</a></p>
      <p id="slogan" class="theme-text-color header">我刚洗了个热水澡，生活好像又有了希望</p>
    </header>
    
    <nav class="menu">
      <ul>
        <li><a href="{% url 'index' %}" {% if request.path == "/blog/" %}class="active"{% endif %}>Home</a>
        <li><a href="{% url 'archive' %}" {% if request.path == "/blog/archive/" %}class="active"{% endif %}>Archive</a>
        <li><a href="{% url 'about-this-blog' %}" {% if request.path == "/blog/about-this-blog" %}class="active"{% endif %}>About this blog</a>
        <li><a href="{% url 'about-me' %}" {% if request.path == "/blog/about-me" %}class="active"{% endif %}>About me</a>
      </ul>
      <form action="">
        <label for="search"></label>
        <input id="search">
      </form>
    </nav>
    
    <main>
      <div id="article-container">
        {% block content %}{% endblock %}
      </div>

      {% block sidebar %}
      <div id="sidebar">
        {% load sidebar %}
        {% sidebar_context as context %}

        {% if context.blog_list %}
        <div class="category">
          <p>Category</p>
          <ul>
            {% for category in context.tag_list %}
            <li><a class="theme-text-color archive" href="{% url 'blog-tag-archive' category.tag %}">{{ category.tag }}</a>
            {% endfor %}
          </ul>
        </div>

        <div class="date">
          <p>Date</p>
          <ul>
            {% for date in context.date_list %}
            <li><a class="theme-text-color archive" href="{% url 'blog-year-archive' date.year %}">{{ date|date:"Y" }}</a>
            {% endfor %}
          </ul>
        </div>
        {% endif %}

        {% if perms.blog.add_blog %}
          <div class="blog-add">
            <a class="theme-text-color form-action" href="{% url 'blog-add' %}">Add new blog</a>
          </div>
        {% endif %}
      </div>
      {% endblock %}
    </main>

    {% block pagination %}
      {% if is_paginated %}
        <div class="pagination">
          <span class="page-links">
            {% if page_obj.has_previous %}
              <a href="{{ request.path }}?page={{ page_obj.previous_page_number }}">previous</a>
            {% endif %}
            <span class="page-current">
              Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
            </span>
            {% if page_obj.has_next %}
            <a href="{{ request.path }}?page={{ page_obj.next_page_number }}">next</a>
            {% endif %}
          </span>
        </div>
      {% endif %}
    {% endblock %}

    <footer class="theme-background theme-text-color footer">
      Based on Django. NeoEase-like theme.
    </footer>

blog/templates/index.html
{% extends "base_generic.html" %}

{% block content %}
  {% if latest %}
    {% for blog in latest %}
    <article>
      <h1>
        <a class="theme-text-color blog-title" href="{{ blog.get_absolute_url }}"><strong>{{ blog.title }}</strong></a>
        {% if perms.blog.change_blog or perms.blog.delete_blog %}
        <span class="blog-title-buttons">
          {% if perms.blog.change_blog %}
          <a class="theme-text-color form-action" href="{% url 'blog-update' blog.post_date.year blog.post_date.month blog.post_date.day blog.slug %}">Edit</a>
          {% endif %}

          {% if perms.blog.delete_blog %}
          <a class="theme-text-color form-action" href="{% url 'blog-delete' blog.post_date.year blog.post_date.month blog.post_date.day blog.slug %}">Delete</a>
          {% endif %}
        </span>
        {% endif %}
      </h1>

      <div class="info">
        <span class="date">{{ blog.post_date|date:"Y.m.d" }}</span>
        <span class="comments">{{ blog.blogcomment_set.all.count }} comments</span>
      </div>
  
      <div>
      {% load martortags %}
      {{ blog.content|safe_markdown }}
      </div>

      <div class="tags">
        {% for tag in blog.tags.all %}
        <a class="theme-text-color archive" href="{% url 'blog-tag-archive' tag.tag %}">{{ tag.tag }}</a>
        {% endfor %}
      </div>
    </article>
    {% endfor %}
  {% else %}
    <p>There are no blogs in this site.</p>
  {% endif %}
{% endblock%}